# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

.zigbee_dependencies: &zigbee_dependencies
  depends_components:
    - ieee802154
  depends_filepatterns:
    - examples/zigbee/light_sample/**/*

examples/zigbee/esp_zigbee_gateway:
  enable:
    - if: SOC_WIFI_SUPPORTED == 1 and IDF_TARGET not in ["esp32c2", "esp32c61", "esp32c5"]
      reason: not supported esp32c2, esp32c61 and esp32c5
  <<: *zigbee_dependencies

examples/zigbee/light_sample:
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1 and IDF_TARGET not in ["esp32c5"]
      reason: zigbee on esp32c5 is only supported in idf master
  disable_test:
    - if: IDF_TARGET != "esp32h2"
      temporary: true
      reason: only test on esp32h2
  <<: *zigbee_dependencies
